// @ts-nocheck
import { MessageMethod } from './message';
import { NotificationMethod } from './notification';
import { ModalMethod } from './modal';
import { DrawerMethod } from './drawer';

declare module 'vue' {
  export interface GlobalComponents {
    AAffix: typeof import('@uno-arco/web-vue')['Affix'];
    AAlert: typeof import('@uno-arco/web-vue')['Alert'];
    AAnchor: typeof import('@uno-arco/web-vue')['Anchor'];
    AAnchorLink: typeof import('@uno-arco/web-vue')['AnchorLink'];
    AAutoComplete: typeof import('@uno-arco/web-vue')['AutoComplete'];
    AAvatar: typeof import('@uno-arco/web-vue')['Avatar'];
    AAvatarGroup: typeof import('@uno-arco/web-vue')['AvatarGroup'];
    ABackTop: typeof import('@uno-arco/web-vue')['BackTop'];
    ABadge: typeof import('@uno-arco/web-vue')['Badge'];
    ABreadcrumb: typeof import('@uno-arco/web-vue')['Breadcrumb'];
    ABreadcrumbItem: typeof import('@uno-arco/web-vue')['BreadcrumbItem'];
    AButton: typeof import('@uno-arco/web-vue')['Button'];
    AButtonGroup: typeof import('@uno-arco/web-vue')['ButtonGroup'];
    ACalendar: typeof import('@uno-arco/web-vue')['Calendar'];
    ACard: typeof import('@uno-arco/web-vue')['Card'];
    ACardMeta: typeof import('@uno-arco/web-vue')['CardMeta'];
    ACardGrid: typeof import('@uno-arco/web-vue')['CardGrid'];
    ACarousel: typeof import('@uno-arco/web-vue')['Carousel'];
    ACarouselItem: typeof import('@uno-arco/web-vue')['CarouselItem'];
    ACascader: typeof import('@uno-arco/web-vue')['Cascader'];
    ACascaderPanel: typeof import('@uno-arco/web-vue')['CascaderPanel'];
    ACheckbox: typeof import('@uno-arco/web-vue')['Checkbox'];
    ACheckboxGroup: typeof import('@uno-arco/web-vue')['CheckboxGroup'];
    ACollapse: typeof import('@uno-arco/web-vue')['Collapse'];
    ACollapseItem: typeof import('@uno-arco/web-vue')['CollapseItem'];
    AColorPicker: typeof import('@uno-arco/web-vue')['ColorPicker'];
    AComment: typeof import('@uno-arco/web-vue')['Comment'];
    AConfigProvider: typeof import('@uno-arco/web-vue')['ConfigProvider'];
    ADatePicker: typeof import('@uno-arco/web-vue')['DatePicker'];
    AWeekPicker: typeof import('@uno-arco/web-vue')['WeekPicker'];
    AMonthPicker: typeof import('@uno-arco/web-vue')['MonthPicker'];
    AYearPicker: typeof import('@uno-arco/web-vue')['YearPicker'];
    AQuarterPicker: typeof import('@uno-arco/web-vue')['QuarterPicker'];
    ARangePicker: typeof import('@uno-arco/web-vue')['RangePicker'];
    ADescriptions: typeof import('@uno-arco/web-vue')['Descriptions'];
    ADescriptionsItem: typeof import('@uno-arco/web-vue')['DescriptionsItem'];
    ADivider: typeof import('@uno-arco/web-vue')['Divider'];
    ADrawer: typeof import('@uno-arco/web-vue')['Drawer'];
    ADropdown: typeof import('@uno-arco/web-vue')['Dropdown'];
    ADoption: typeof import('@uno-arco/web-vue')['Doption'];
    ADgroup: typeof import('@uno-arco/web-vue')['Dgroup'];
    ADsubmenu: typeof import('@uno-arco/web-vue')['Dsubmenu'];
    AEmpty: typeof import('@uno-arco/web-vue')['Empty'];
    AForm: typeof import('@uno-arco/web-vue')['Form'];
    AFormItem: typeof import('@uno-arco/web-vue')['FormItem'];
    AGrid: typeof import('@uno-arco/web-vue')['Grid'];
    AGridItem: typeof import('@uno-arco/web-vue')['GridItem'];
    ACol: typeof import('@uno-arco/web-vue')['Col'];
    ARow: typeof import('@uno-arco/web-vue')['Row'];
    AImage: typeof import('@uno-arco/web-vue')['Image'];
    AImagePreview: typeof import('@uno-arco/web-vue')['ImagePreview'];
    AImagePreviewAction: typeof import('@uno-arco/web-vue')['ImagePreviewAction'];
    AImagePreviewGroup: typeof import('@uno-arco/web-vue')['ImagePreviewGroup'];
    AInput: typeof import('@uno-arco/web-vue')['Input'];
    AInputGroup: typeof import('@uno-arco/web-vue')['InputGroup'];
    AInputSearch: typeof import('@uno-arco/web-vue')['InputSearch'];
    AInputPassword: typeof import('@uno-arco/web-vue')['InputPassword'];
    AInputNumber: typeof import('@uno-arco/web-vue')['InputNumber'];
    AInputTag: typeof import('@uno-arco/web-vue')['InputTag'];
    ALayout: typeof import('@uno-arco/web-vue')['Layout'];
    ALayoutHeader: typeof import('@uno-arco/web-vue')['LayoutHeader'];
    ALayoutContent: typeof import('@uno-arco/web-vue')['LayoutContent'];
    ALayoutFooter: typeof import('@uno-arco/web-vue')['LayoutFooter'];
    ALayoutSider: typeof import('@uno-arco/web-vue')['LayoutSider'];
    ALink: typeof import('@uno-arco/web-vue')['Link'];
    AList: typeof import('@uno-arco/web-vue')['List'];
    AListItem: typeof import('@uno-arco/web-vue')['ListItem'];
    AListItemMeta: typeof import('@uno-arco/web-vue')['ListItemMeta'];
    AMention: typeof import('@uno-arco/web-vue')['Mention'];
    AMenu: typeof import('@uno-arco/web-vue')['Menu'];
    AMenuItem: typeof import('@uno-arco/web-vue')['MenuItem'];
    AMenuItemGroup: typeof import('@uno-arco/web-vue')['MenuItemGroup'];
    ASubMenu: typeof import('@uno-arco/web-vue')['SubMenu'];
    AModal: typeof import('@uno-arco/web-vue')['Modal'];
    APageHeader: typeof import('@uno-arco/web-vue')['PageHeader'];
    APagination: typeof import('@uno-arco/web-vue')['Pagination'];
    APopconfirm: typeof import('@uno-arco/web-vue')['Popconfirm'];
    APopover: typeof import('@uno-arco/web-vue')['Popover'];
    AProgress: typeof import('@uno-arco/web-vue')['Progress'];
    ARadio: typeof import('@uno-arco/web-vue')['Radio'];
    ARadioGroup: typeof import('@uno-arco/web-vue')['RadioGroup'];
    ARate: typeof import('@uno-arco/web-vue')['Rate'];
    AResizeBox: typeof import('@uno-arco/web-vue')['ResizeBox'];
    AResult: typeof import('@uno-arco/web-vue')['Result'];
    ASelect: typeof import('@uno-arco/web-vue')['Select'];
    AOption: typeof import('@uno-arco/web-vue')['Option'];
    AOptgroup: typeof import('@uno-arco/web-vue')['Optgroup'];
    ASkeleton: typeof import('@uno-arco/web-vue')['Skeleton'];
    ASkeletonLine: typeof import('@uno-arco/web-vue')['SkeletonLine'];
    ASkeletonShape: typeof import('@uno-arco/web-vue')['SkeletonShape'];
    ASlider: typeof import('@uno-arco/web-vue')['Slider'];
    ASpace: typeof import('@uno-arco/web-vue')['Space'];
    ASpin: typeof import('@uno-arco/web-vue')['Spin'];
    ASplit: typeof import('@uno-arco/web-vue')['Split'];
    AStatistic: typeof import('@uno-arco/web-vue')['Statistic'];
    ACountdown: typeof import('@uno-arco/web-vue')['Countdown'];
    ASteps: typeof import('@uno-arco/web-vue')['Steps'];
    AStep: typeof import('@uno-arco/web-vue')['Step'];
    ASwitch: typeof import('@uno-arco/web-vue')['Switch'];
    ATable: typeof import('@uno-arco/web-vue')['Table'];
    AThead: typeof import('@uno-arco/web-vue')['Thead'];
    ATd: typeof import('@uno-arco/web-vue')['Td'];
    ATh: typeof import('@uno-arco/web-vue')['Th'];
    ATr: typeof import('@uno-arco/web-vue')['Tr'];
    ATbody: typeof import('@uno-arco/web-vue')['Tbody'];
    ATableColumn: typeof import('@uno-arco/web-vue')['TableColumn'];
    ATabs: typeof import('@uno-arco/web-vue')['Tabs'];
    ATabPane: typeof import('@uno-arco/web-vue')['TabPane'];
    ATag: typeof import('@uno-arco/web-vue')['Tag'];
    ATextarea: typeof import('@uno-arco/web-vue')['Textarea'];
    ATimePicker: typeof import('@uno-arco/web-vue')['TimePicker'];
    ATimeline: typeof import('@uno-arco/web-vue')['Timeline'];
    ATimelineItem: typeof import('@uno-arco/web-vue')['TimelineItem'];
    ATooltip: typeof import('@uno-arco/web-vue')['Tooltip'];
    ATransfer: typeof import('@uno-arco/web-vue')['Transfer'];
    ATree: typeof import('@uno-arco/web-vue')['Tree'];
    ATreeSelect: typeof import('@uno-arco/web-vue')['TreeSelect'];
    ATrigger: typeof import('@uno-arco/web-vue')['Trigger'];
    ATypography: typeof import('@uno-arco/web-vue')['Typography'];
    ATypographyParagraph: typeof import('@uno-arco/web-vue')['TypographyParagraph'];
    ATypographyTitle: typeof import('@uno-arco/web-vue')['TypographyTitle'];
    ATypographyText: typeof import('@uno-arco/web-vue')['TypographyText'];
    AUpload: typeof import('@uno-arco/web-vue')['Upload'];
    AVerificationCode: typeof import('@uno-arco/web-vue')['VerificationCode'];
    AWatermark: typeof import('@uno-arco/web-vue')['Watermark'];
  }

  export interface ComponentCustomProperties {
    $message: MessageMethod;
    $notification: NotificationMethod;
    $modal: ModalMethod;
    $drawer: DrawerMethod;
  }
}

export {};
