blank_issues_enabled: true
contact_links:
  - name: Official Arco Design Vue
    url: https://github.com/arco-design/arco-design-vue
    about: This repository is a community fork. The original project lives here.
